name: test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'site/**'

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - run: echo "module.exports = ${{ toJson(github.event) }}" >> json.js
      - run: cat json.js
      - uses: actions/github-script@v7
        with:
          script: |
            const json = require('./json.js');
            console.log(JSON.stringify(json, null, 2));
